#' Cut data for completers analysis
#'
#' Subsets the data to subjects who have completed follow-up by the specified date,
#' and prepares the data for analysis.
#'
#' @param data Data generated by [nb_sim()].
#' @param cut_date Calendar time (relative to trial start) at which to cut the data.
#' @param event_gap Gap duration after each event during which no new events are counted.
#'   Can be a numeric value (default `5 / 365.25`) or a function returning a numeric value.
#'   The time at risk is reduced by the sum of these gaps (truncated by the cut date).
#'
#' @return A data frame with one row per subject who has completed follow-up by `cut_date`.
#'   Contains the truncated follow-up time (`tte`) and total number of observed events (`events`).
#'
#' @examples
#' enroll_rate <- data.frame(rate = 20 / (5 / 12), duration = 5 / 12)
#' fail_rate <- data.frame(treatment = c("Control", "Experimental"), rate = c(0.5, 0.3))
#' dropout_rate <- data.frame(
#'   treatment = c("Control", "Experimental"),
#'   rate = c(0.1, 0.05), duration = c(100, 100)
#' )
#' sim <- nb_sim(enroll_rate, fail_rate, dropout_rate, max_followup = 2, n = 20)
#' # Find date when 5 subjects have completed
#' date_5 <- cut_date_for_completers(sim, 5)
#' # Get analysis dataset for these completers
#' cut_completers(sim, date_5)
#' @export
cut_completers <- function(data, cut_date, event_gap = 5 / 365.25) {
  if (is.null(cut_date) || length(cut_date) != 1L || !is.finite(cut_date)) {
    stop("cut_date must be a single finite numeric value", call. = FALSE)
  }

  dt <- data.table::as.data.table(data)
  
  # Determine max_followup from the data (assuming at least one completer or close to it)
  # In nb_sim, completers have tte = max_followup. Dropouts have tte < max_followup.
  # We assume the maximum observed tte is the max_followup.
  max_f <- max(dt$tte)
  
  # Identify completers: subjects whose max tte is (approx) equal to max_f
  # We use a small tolerance for floating point comparisons
  completers_dt <- dt[, .(is_completer = max(tte) >= max_f - 1e-8,
                          completion_time = first(enroll_time) + max(tte)), by = id]
  
  # Filter for subjects who are completers AND finished by cut_date
  completed_ids <- completers_dt[is_completer & completion_time <= cut_date, id]
  
  if (length(completed_ids) == 0) {
    return(data.frame(
      id = integer(0), treatment = character(0), enroll_time = numeric(0),
      tte = numeric(0), events = integer(0)
    ))
  }
  
  # Subset original data to these subjects
  subset_data <- dt[id %in% completed_ids]
  class(subset_data) <- class(data) # Preserve class for cut_data_by_date method dispatch
  
  # Use cut_data_by_date to generate the analysis variables
  # Since they have completed by cut_date, this will return their full follow-up info
  cut_data_by_date(subset_data, cut_date, event_gap = event_gap)
}

#' Find calendar date for target completer count
#'
#' Finds the calendar time (since start of randomization) at which a specified
#' number of subjects have completed their follow-up.
#'
#' @param data A data frame of simulated data, typically from [nb_sim()].
#' @param target_completers Integer. The target number of completers.
#'
#' @return Numeric. The calendar date when `target_completers` is achieved.
#'   If the dataset contains fewer than `target_completers` completers, returns the maximum
#'   calendar time in the dataset and prints a message.
#'
#' @export
cut_date_for_completers <- function(data, target_completers) {
  dt <- data.table::as.data.table(data)
  
  # Determine max_followup
  max_f <- max(dt$tte)
  
  # Identify completers and their completion times
  # Completers are those who reached max_f (did not drop out)
  # Their completion time is enroll_time + tte (where tte = max_f)
  # We look at the last record for each ID which holds the max tte
  
  # Get last row per ID
  last_rows <- dt[, .SD[.N], by = id]
  
  # Filter for completers
  # tte must be max_f
  completers <- last_rows[tte >= max_f - 1e-8]
  
  if (nrow(completers) < target_completers) {
    message(sprintf("Only %d completers in trial (target: %d)", nrow(completers), target_completers))
    return(max(dt$calendar_time))
  }
  
  # Sort completion times
  completion_times <- sort(completers$calendar_time)
  
  # Return the date the target-th completer finished
  return(completion_times[target_completers])
}

