#' Cut data for completers analysis
#'
#' Subsets the data to all subjects randomized by the specified date,
#' and prepares the data for analysis. This is a wrapper for [cut_data_by_date()]
#' typically used with a date determined by [cut_date_for_completers()].
#'
#' @param data Data generated by [nb_sim()].
#' @param cut_date Calendar time (relative to trial start) at which to cut the data.
#' @param event_gap Gap duration after each event during which no new events are counted.
#'   Can be a numeric value (default `5 / 365.25`) or a function returning a numeric value.
#'   The time at risk is reduced by the sum of these gaps (truncated by the cut date).
#'
#' @return A data frame with one row per subject randomized prior to `cut_date`.
#'   Contains the truncated follow-up time (`tte`) and total number of observed events (`events`).
#'
#' @export
#'
#' @examples
#' enroll_rate <- data.frame(rate = 20 / (5 / 12), duration = 5 / 12)
#' fail_rate <- data.frame(treatment = c("Control", "Experimental"), rate = c(0.5, 0.3))
#' dropout_rate <- data.frame(
#'   treatment = c("Control", "Experimental"),
#'   rate = c(0.1, 0.05), duration = c(100, 100)
#' )
#' sim <- nb_sim(enroll_rate, fail_rate, dropout_rate, max_followup = 2, n = 20)
#' # Find date when 5 subjects have completed
#' date_5 <- cut_date_for_completers(sim, 5)
#' # Get analysis dataset for this cut date (includes partial follow-up)
#' cut_completers(sim, date_5)
cut_completers <- function(data, cut_date, event_gap = 5 / 365.25) {
  cut_data_by_date(data, cut_date, event_gap = event_gap)
}

#' Find calendar date for target completer count
#'
#' Finds the calendar time (since start of randomization) at which a specified
#' number of subjects have completed their follow-up.
#'
#' @param data A data frame of simulated data, typically from [nb_sim()].
#' @param target_completers Integer. The target number of completers.
#'
#' @return Numeric. The calendar date when `target_completers` is achieved.
#'   If the dataset contains fewer than `target_completers` completers, returns the maximum
#'   calendar time in the dataset and prints a message.
#'
#' @export
#'
#' @examples
#' enroll_rate <- data.frame(rate = 20 / (5 / 12), duration = 5 / 12)
#' fail_rate <- data.frame(treatment = c("Control", "Experimental"), rate = c(0.5, 0.3))
#' dropout_rate <- data.frame(
#'   treatment = c("Control", "Experimental"),
#'   rate = c(0.1, 0.05), duration = c(100, 100)
#' )
#' sim <- nb_sim(enroll_rate, fail_rate, dropout_rate, max_followup = 2, n = 20)
#' cut_date_for_completers(sim, target_completers = 5)
cut_date_for_completers <- function(data, target_completers) {
  dt <- data.table::as.data.table(data)

  # Determine max_followup
  max_f <- max(dt$tte)

  # Identify completers and their completion times
  # Completers are those who reached max_f (did not drop out)
  # Their completion time is enroll_time + tte (where tte = max_f)
  # We look at the last record for each ID which holds the max tte

  # Get last row per ID
  last_rows <- dt[, .SD[.N], by = id]

  # Filter for completers
  # tte must be max_f
  completers <- last_rows[tte >= max_f - 1e-8]

  if (nrow(completers) < target_completers) {
    message(sprintf("Only %d completers in trial (target: %d)", nrow(completers), target_completers))
    return(max(dt$calendar_time))
  }

  # Sort completion times
  completion_times <- sort(completers$calendar_time)

  # Return the date the target-th completer finished
  return(completion_times[target_completers])
}
